services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: a
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
